FROM alpine:latest

RUN apk add --no-cache privoxy && \
    echo "listen-address 0.0.0.0:8118" >> /etc/privoxy/config && \
    echo "forward-socks5 / warp-proxy:1080 ." >> /etc/privoxy/config

EXPOSE 8118

CMD ["privoxy", "--no-daemon", "--user", "privoxy", "/etc/privoxy/config"]
